# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: gitversion/setup@0
  inputs:
    versionSpec: '5.6.6'

- task: gitversion/execute@0
  inputs:
    useConfigFile: true
    configFilePath: GitVersion.yml
- task: printAllVariables@1
- task: TfxInstaller@3
  inputs:
    version: '>=v0.7.x'
- task: PackageAzureDevOpsExtension@3
  inputs:
    rootFolder: './'
    publisherId: 'timschaeps'
    extensionId: 'ScriptArgumentParser'
    extensionName: 'Script Argument Parser'
    extensionVersion: '$(GitVersion.MajorMinorPatch).$(PreReleaseNumber )'
    updateTasksVersion: true
    extensionVisibility: 'private_preview'

