# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

steps:
- task: gitversion/setup@0
  inputs:
    versionSpec: '5.6.6'

- task: gitversion/execute@0
  inputs:
    useConfigFile: true
    configFilePath: GitVersion.yml
- task: printAllVariables@1
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'install --only=prod'
- task: TfxInstaller@3
  inputs:
    version: '>=v0.7.x'
- task: PackageAzureDevOpsExtension@3
  inputs:
    rootFolder: './'
    publisherId: 'pierredeconynck'
    extensionId: 'ScriptArgumentParserTst'
    extensionVersion: '$(GitVersion.Major).$(GitVersion.Minor).$(GitVersion.PreReleaseNumber)'
    updateTasksVersion: true
    extensionVisibility: 'public'

